services:
  postgres:
    image: postgres:18
    container_name: pg_notif
    environment:
      POSTGRES_DB: notif
      POSTGRES_USER: notif
      POSTGRES_PASSWORD: notif
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: redis_notif
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka_notif
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_NODE_ID=1
      
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    ports:
      - "9092:9092"